### ISSUE TITLE
Why remove all line endings?

### ISSUE THREAD

**Issue by evandrocoan** [spywhere/JavatarPackages#1]
I think it is not nice to remove all line endings:

![image](https://cloud.githubusercontent.com/assets/5332158/25867339/a8c376da-34cf-11e7-8f58-e13f264bfc0c.png)

May be the indentation and line ends, would be too big for the file. But as it seems the file is just for settings, to group the packages.

**Comment by spywhere** [comment]
These files are used for working with import organization. And also intended to be used for autocompletion at that time (as `tags` help with type information). As each file will be downloaded separately and without any compression, remove all those whitespaces help decrease the file size (even a bit). Although you might want to read this, I think JavaDoc is quite good enough for API references. However, if you want to use these files for another project, you could regenerate it again (using `JavatarDoc` though).
